### ISSUE TITLE
VS Code integration no longer working

### ISSUE THREAD

**Issue by rendaw** [segmentio/golines#20]
I may be doing something wrong, but again same thing with `gofumpt`: https://github.com/mvdan/gofumpt/issues/83

I opened https://github.com/golang/go/issues/42015 but if someone more knowledgeable could confirm or perhaps provide details it would be appreciated.

**Comment by yolken-segment** [comment]
Thanks for the report, will try to figure out the latest way to integrate this tool with VSCode.

**Comment by agungwk** [comment]
I'm having same issue, but here's my workaround

Install VSCode extension https://github.com/emeraldwalk/vscode-runonsave
Then on `settings.json` add these configuration
```
"emeraldwalk.runonsave": {
        "commands": [
            {
                "match": "\\.go$",
                "cmd": "golines ${file} -w --base-formatter=\"gofmt\""
            },
        ]
    },
```
May it helps you

**Comment by yolken-segment** [comment]
Confirmed that this works well- thanks @agungwk. Will update the README soon.
