### ISSUE TITLE
Formatting for very long if statement doesn't work as expected

### ISSUE THREAD

**Issue by Merteg** [segmentio/golines#30]
golines just moved the last part of my if statement to another line, but other statements still on the same line (and it is still extremely long)

Attaching screenshot that I got using dry-run
![зображення](https://user-images.githubusercontent.com/18135784/115716310-b94ef400-a381-11eb-9918-76eefecb0993.png)

**Comment by Merteg** [comment]
I played with your library a little bit and was able to fix an issue.
Instead of doing `e.Y.Decorations().Before = dst.NewLine` here: https://github.com/segmentio/golines/blob/master/shortener.go#L499
You can do this:
```
if e.Y.Decorations().Before == dst.NewLine {
	s.formatExpr(e.X, force, isChain)
} else {
	e.Y.Decorations().Before = dst.NewLine
}
```
If it looks fine I can make a PR (but seems like users are restricted from creating branches)

**Comment by yolken-segment** [comment]
Oh, nice- yes, feel free to create a PR. You should be able to fork the repo and then create a new pull request from a branch in your fork? Then, it will show up here and we can review together.

**Comment by Merteg** [comment]
Got it, I'll do that
I'll think about fix more, maybe I miss something

**Comment by Merteg** [comment]
PR is ready
Check it, please: https://github.com/segmentio/golines/pull/31

**Comment by yolken-segment** [comment]
Fixed by https://github.com/segmentio/golines/pull/31.
