### ISSUE TITLE
Long method signatures containing interfaces are not broken up

### ISSUE THREAD

**Issue by StevenACoffman** [segmentio/golines#40]
When I use my IDE (GoLand) to refactor a method signature by adding, removing, or reordering arguments, they wind up all on one line:
```
func CreateEphemeralRecordEvent(ctx interface {
	kacontext.Base
	datastore.KAContext
	timectx.KAContext
}, id string, name string, kaid string, districtID string, status models.EphemeralStatus ) (*models.EphemeralRecordEvent, error) {
```
golines will leave these alone, but I would have expected (and wanted): 
```
func CreateEphemeralRecordEvent(
	ctx interface {
		kacontext.Base
		datastore.KAContext
		timectx.KAContext
	}, 
	id string,
	name string,
	kaid string,
	districtID string,
	status models.EphemeralStatus,
) (*models.EphemeralRecordEvent, error) {
```

I'm not actually sure if it is the presence of the interface that is causing these to be ignored by golines.

**Comment by yolken-segment** [comment]
This should be fixed in https://github.com/segmentio/golines/pull/46. Thanks for the report, and let me know if the new version doesn't work as expected.
