### ISSUE TITLE
not found in vscode

### ISSUE THREAD

**Issue by mcauto** [segmentio/golines#41]
hello! 
I like this module :)
but I have an issue.

I use golines in vscode with WSL2.
below error occur.

```bash
# vscode output (save on run)
Running on save commands...
*** cmd start: golines file.go -w
Run on Save done.
/bin/sh: 1: golines: not found
```

```bash
# terminal
golines --version
golines v0.5.0
```

**settings.json**  
```json
{
  "go.buildOnSave": "package",
  "go.lintOnSave": "file",
  "go.vetOnSave": "package",
  "go.coverOnSave": false,
  "go.testOnSave": true,
  "go.useCodeSnippetsOnFunctionSuggest": false,
  "go.buildTags": "",
  "go.buildFlags": [],
  "go.lintFlags": [],
  "go.vetFlags": [],
  "go.formatTool": "goreturns",
  "go.lintTool": "golint",
  "go.docsTool": "godoc",
  "go.gocodeAutoBuild": false,
  "editor.formatOnSave": true,
  // go get -u github.com/segmentio/golines
  "emeraldwalk.runonsave": {
    "commands": [
      {
        "match": "\\.go$",
        "cmd": "golines ${file} -w"
      }
    ]
  },
  "go.testEnvFile": "${workspaceFolder}/.env"
}
```

![image](https://user-images.githubusercontent.com/15080806/141877743-accf3c76-8b21-476d-ac9d-adc63d4b5450.png)

![image](https://user-images.githubusercontent.com/15080806/141877761-1bbf22c6-f114-4ad2-ba68-be8161e2ca21.png)

**Comment by yolken-segment** [comment]
Is the go binary directory (where `golines` is installed by default) in your `PATH`? You can also just replace the `cmd` value in your settings with the full path to the binary, e.g. `/Users/my-user/.../.../golines`.

**Comment by mcauto** [comment]
I solved it :)

`vscode` recognize 1.13, however `go.mod` is 1.17

update settings.json below
```
{
...
  "go.goroot": "/usr/local/go",
}
```
