### ISSUE TITLE
Specifying base-formatter causes golines to not shorten anything

### ISSUE THREAD

**Issue by fgblomqvist** [segmentio/golines#44]
Running this with latest golines:
```
golines --base-formatter "cat test.go" -m 120 test.go
```
Where `test.go` contains:
```go
package main

import "fmt"

func MyLongFunction(one, two, three, four, five, six, seven, eight, nine, ten, eleven string) {
	fmt.Println("Hello world!")
}
```

```
$ golines --base-formatter "cat test.go" -m 50 test.go 
package main

import "fmt"

func MyLongFunction(one, two, three, four, five, six, seven, eight, nine, ten, eleven string) {
        fmt.Println("Hello world!")
}
$ golines -m 50 test.go 
package main

import "fmt"

func MyLongFunction(
        one, two, three, four, five, six, seven, eight, nine, ten, eleven string,
) {
        fmt.Println("Hello world!")
}
```

Naturally one would specify an actually useful base-formatter, but this is just to make the case.

**Comment by yolken-segment** [comment]
This is the expected behavior in this case. After each shortening round, it runs the base formatter and replaces the current, in-memory version of the file with the output of the shortener. If you give it `cat test.go`, then it will literally use the original file (which is not updated until the end) as the replacement.

Hope this helps.

**Comment by fgblomqvist** [comment]
Oh I see, so the base formatter needs to read from stdin AND output to stdout? Maybe the docs could be updated to clarify that

**Comment by yolken-segment** [comment]
Yes, that's correct! I'll update the docs in the next change, thanks for the feedback.

**Comment by yolken-segment** [comment]
The documentation here was improved in https://github.com/segmentio/golines/pull/46.
