### ISSUE TITLE
Generic type parameters stripped, if file includes struct tags with more than one key

### ISSUE THREAD

**Issue by bakape** [segmentio/golines#57]
If the file includes any struct tags possibly needing alignment (meaning there are at least 2 tags on a field), generic parameters from a function later in the file are stripped. 

I have confirmed this is not an issue in the backend formatter with both `gofmt` and `goimports`. 

## Example 

Passing

```go
package strips_generics

type needsTagAllignemnt struct {
        Foo  *bool   `json:"foo" db:"foo"`
}


// Has its type parameters stripped
func setDefault[T any](dst **T, val T) {
        if *dst == nil {
                *dst = &val
        }
}
```

into golines with `golines ./main.go` outputs

```go
package strips_generics

type needsTagAllignemnt struct {
        Foo *bool `json:"foo" db:"foo"`
}

// Has its type parameters stripped
func setDefault(dst **T, val T) {
        if *dst == nil {
                *dst = &val
        }
}

```

Code with accompanying `go.mod`: [test.zip](https://github.com/segmentio/golines/files/8283793/test.zip)

**Comment by bakape** [comment]
For anyone also affected by this, I have found that moving generics before any multi field struct tags negates the issues as a temporary workaround.

**Comment by yolken** [comment]
I think there's a more general issue here independent of the struct tag features- I filed https://github.com/segmentio/golines/issues/61 to track.

Sorry about this.

**Comment by bakape** [comment]
Interesting, that the issue can be avoided by putting the generics at the
start of the file.

Either way, thanks for the clarification!

**Comment by yolken** [comment]
Generics support should be fixed by https://github.com/segmentio/golines/pull/68. Please reopen if you continue to see the issue with the latest `golines` version. Thanks.

**Comment by bakape** [comment]
Okay, thank you!

**Comment by Vitomir2** [comment]
Hey,

@yolken @bakape, how did you solve this one? I am using v0.9.0 and when I save the file, it still deletes my generic type struct.

This:
```
type eventsGetter[T contractsapi.EventAbi] struct {
	receiptsGetter
	// parseEventFn is a plugin function used to parse the event from transaction log
	parseEventFn func(*types.Header, *ethgo.Log) (T, bool, error)
	// isValidLogFn is a plugin function that validates the log
	// for example: if it was sent from the desired address
	isValidLogFn func(*types.Log) bool
}
```

is formatted to this:
```
type eventsGetter struct {
	receiptsGetter
	// parseEventFn is a plugin function used to parse the event from transaction log
	parseEventFn func(*types.Header, *ethgo.Log) (T, bool, error)
	// isValidLogFn is a plugin function that validates the log
	// for example: if it was sent from the desired address
	isValidLogFn func(*types.Log) bool
}
```

Thus, my code fails because it deletes the generic type of the struct.
