### ISSUE TITLE
Generic type parameters are stripped

### ISSUE THREAD

**Issue by yolken** [segmentio/golines#61]
`golines` does not yet support generic type parameters.

Adapting from the example in the [official generics tutorial](https://go.dev/doc/tutorial/generics):

```
func SumIntsOrFloats[K comparable, V int64 | float64](m map[K]V, longArgument1 int, longArgument2 int, longArgument3 int) V {
	var s V
	for _, v := range m {
		s += v
	}
	return s
}
```

shortens to:

```
func SumIntsOrFloats(
	m map[K]V,
	longArgument1 int,
	longArgument2 int,
	longArgument3 int,
) V {
	var s V
	for _, v := range m {
		s += v
	}
	return s
}
```

which is missing the bracketed type parameters and thus is incorrect.

We depend on https://github.com/dave/dst to generate the ASTs that are used in the shortening process, but unfortunately that library won't be fixed to support generics for a while because the author is currently off-the-grid (see https://github.com/dave/dst/issues/63 for details). I'll follow that issue, and when it's fixed we should be able to fix `golines` as well.

Apologies for any inconvenience caused here.

**Comment by yolken** [comment]
@sirkon nice, thanks. Will give it a try in a bit.

**Comment by mumbleskates** [comment]
Bump, this renders golines unusable on any codebase that uses generics.

**Comment by telemachus** [comment]
> Bump, this renders golines unusable on any codebase that uses generics.

How does this help?

From the linked dst issue, "[Supporting generics] is not a small change, and I will be hiking in Patagonia from December 2021 until April or May 2022 without my laptop, so I won't be able to get this done until I get back."

**Comment by yolken** [comment]
Fixed by https://github.com/segmentio/golines/pull/68.

**Comment by mumbleskates** [comment]
thank you!
