### ISSUE TITLE
gives fatal error on simple test

### ISSUE THREAD

**Issue by Alexey-T** [segmentio/golines#72]
go version go1.18.3 linux/amd64

test file ln.go
```
package ln

myMap := map[string]string{"first key": "first value", "second key": "second value", "third key": "third value", "fourth key": "fourth value", "fifth key": "fifth value"}
```

my test:
```
user@PC:~$ golines<ln.go
[2022-06-09 14:52:33] FATAL Error formatting source: exit status 2

```

**Comment by telemachus** [comment]
That's not a valid go file. You can't use the short form of assignment outside of a function.

Try it like this.

```go
package ln

var myMap = map[string]string{"first key": "first value", "second key": "second value", "third key": "third value", "fourth key": "fourth value", "fifth key": "fifth value"}
```

```shell
$ golines ln.go
package ln

var myMap = map[string]string{"first key": "first value", "second key": "second value", "third key": "third value", "fourth key": "fourth value", "fifth key": "fifth value"}
```

**Comment by AlexisGoodfellow** [comment]
Can this error message give in its output the filename of the source file which is malformed? That would help when running golines on an entire directory to see which file is failing in particular!

**Comment by chrisyxlee** [comment]
> Can this error message give in its output the filename of the source file which is malformed? That would help when running golines on an entire directory to see which file is failing in particular!

You should be able to see which file it is by running with the `-d` or `--debug` parameter. It'll be the last file name the program logs before exiting.

**Comment by chrisyxlee** [comment]
Also what worked for me (when getting `FATAL Error formatting source: exit status 2`) was just adding `--base-formatter gofmt` to my invocation of golines. For some reason, one particular file was failing with golines, but `go fmt <that file` worked. In my case, golines was defaulting to `goimports` instead.

**Comment by telemachus** [comment]
> Also what worked for me (when getting `FATAL Error formatting source: exit status 2`) was just adding `--base-formatter gofmt` to my invocation of golines. For some reason, one particular file was failing with golines, but `go fmt <that file>` worked. In my case, golines was defaulting to `goimports` instead.

That may mean that you need to update `goimports`. Check out [this issue and the linked issues there](https://github.com/segmentio/golines/issues/96).
