### ISSUE TITLE
fails with exit code 2 and no error message

### ISSUE THREAD

**Issue by hellt** [segmentio/golines#76]
Hi, I have a short file that causes golines to abruptly fail without indication what went wrong.

Here is the file - https://gist.github.com/hellt/bf38f4b294a567157d5edfa271349dda

Any clues on what causes it to fail?

**Comment by telemachus** [comment]
I can't reproduce that here. (That is, I have no problem if I run golines on that file.)

Can you say a little more about the context? Is there maybe something else that's causing the problem?

Also, what versions of go and golines are you using?

**Comment by hellt** [comment]
I am sorry @telemachus I forgot to attach the steps to reproduce that.

I have tried 0.10.0 and 0.8.0, here is what I did for 0.10.0 built with [this dockerfile](https://github.com/hellt/dockerfiles/blob/main/golines/golines.dockerfile)

```
docker run --rm -it ghcr.io/hellt/golines:0.10.0 

apk add curl

curl -o /tmp/src.go https://gist.githubusercontent.com/hellt/bf38f4b294a567157d5edfa271349dda/raw/ace367bbdfe975d6b677985d5e3e4fcb922c2ed4/types.go

golines --version
golines v0.10.0

golines -w /tmp/src.go 
[2022-07-26 14:43:03] FATAL Error formatting source: exit status 2
```

I think this might be related to go-imports

**Comment by telemachus** [comment]
> I think this might be related to go-imports

I agree, sort of. The problem starts from `goimports`, but I guess it has to do with the larger set-up of the docker machine.

Here's what I get if I log in interactively and run `goimports /tmp/types.go`:

```shell
/work # goimports /tmp/src.go
err: go command required, not found: exec: "go": executable file not found in $PATH: stderr:
```

Also, you may want to update the Dockerfile to use `golang:1.18-alpine`. I get a warning with 1.17-alpine because the dependencies of golines@latest require go 1.18.

**Comment by hellt** [comment]
Ohhh. I forgot that goimports need go toolchain. Will rebuild the container and this should fix it. Thanks and sorry for wasting your time

**Comment by Meuko** [comment]
@hellt Did you manage to fix this? I'm currently also running into this issue in my local development suite, there's a single file in my project that breaks golines for some reason. Scoped it down to setting object values (lines aren't even long).

**Comment by hellt** [comment]
I have fixed this particular issue by using a container with Go toolchain
installed.
But then I started to experience hangs which I couldn't fix so far
