### ISSUE TITLE
Integrate with VSCode?

### ISSUE THREAD

**Issue by kjico** [segmentio/golines#8]
Is it possible to integrate and use this with vscode?

**Comment by yolken-segment** [comment]
Hi- I actually filed an issue in the `vscode-go` project about this: https://github.com/microsoft/vscode-go/issues/2990. The solution they proposed isn't the prettiest, but it should work. I'll update the README with the details in case other people are wondering as well.

**Comment by yolken-segment** [comment]
Fixed by https://github.com/segmentio/golines/pull/10.
