### ISSUE TITLE
command not found after install

### ISSUE THREAD

**Issue by tawanchaiii** [segmentio/golines#85]
I tried to run `golines` command 
but command not found when call `golines`
I found package on `~/go/pkg/mod/github.com/segmentio/golines@v0.11.0`

`go version` = `go version go1.19.1 darwin/arm64` (Macbook Air M1)

**Comment by tawanchaiii** [comment]
I found the problem. 
You need to use `sudo` before installing the package.

The solution.
`sudo go install github.com/segmentio/golines@latest`

**Comment by telemachus** [comment]
For future Googlers: you shouldn't normally need to use `sudo`. I think that depends on the user's `PATH` and go installation details.
