### ISSUE TITLE
Comments with long urls add extra blank lines repeatedly

### ISSUE THREAD

**Issue by StevenACoffman** [segmentio/golines#9]
If I have code like:
```go
func GetClient(districtId string) (string, error) {
	districtToken, err := GetCleverToken(districtId)
	if err != nil {
		return "", nil
	}
	// Example BearerToken
	// See:
	// https://swagger.io/docs/specification/authentication/bearer-authentication/
```
And I run `golines -m 78 --shorten-comments -w .`

Then golines will see the line that is too long, and change it to:
```go
func GetClient(districtId string) (string, error) {
	districtToken, err := GetCleverToken(districtId)
	if err != nil {
		return "", nil
	}
	// Example BearerToken
	// See:
	//
	// https://swagger.io/docs/specification/authentication/bearer-authentication/
```
However, every time you run golines it will repeat inserting the blank comment line:
```go
func GetClient(districtId string) (string, error) {
	districtToken, err := GetCleverToken(districtId)
	if err != nil {
		return "", nil
	}
	// Example BearerToken
	// See:
	//
	//
	//
	//
	//
	//
	//
	//
	//
	//
	//
	//
	//
	//
	//
	//
	//
	//
	// https://swagger.io/docs/specification/authentication/bearer-authentication/
```
It would be nice if either comments containing only a single, long unbreakable string (e.g. URL) were special cased, **OR** if the line preceding it was already an empty comment, golines did not insert another one.

Thanks very much for a great tool that has helped me to avoid a lot of wasted time complying with silly linter rules.

**Comment by yolken-segment** [comment]
Thanks for the bug report, and glad you find the tool useful! This issue should be fixed by https://github.com/segmentio/golines/pull/11. Please let me know if this doesn't help, and I can take another look.
