### ISSUE TITLE
Fails with generic function - "Error formatting source: exit status 2"

### ISSUE THREAD

**Issue by karatekaneen** [segmentio/golines#96]
When trying to run golines on a file with a generic function it fails with "Error formatting source: exit status 2".

**Environment**
OS: OSX 12.6.3 - Monterey
Version: 0.11
Go: 1.20.1

### To reproduce
```go
package main

func find[T any](s []T, predicate func(T) bool) (T, bool) {
	for _, item := range s {
		if predicate(item) {
			return item, true
		}
	}
	return s[0], false
}

func main() {
	aVeryLongVariableNameThatWillTrigger := []string{"hello", "world", "hope", "you", "all", "are", "doing", "well"}
	find(aVeryLongVariableNameThatWillTrigger, func(superLongNameAgain string) bool { return superLongNameAgain == "you" })
}
```

**Comment by telemachus** [comment]
I can't reproduce that here, but my guess is that your problem is related to `goimports` being out of date. Take a look at these two old issues.

+ https://github.com/segmentio/golines/issues/76
+ https://github.com/segmentio/golines/issues/75

**Comment by karatekaneen** [comment]
Thank you! You are completely correct and this solved my issue.
